### ISSUE TITLE
validate_uuid(uuid_string)

### ISSUE THREAD

**Issue by roshanjrajan** [logentries/le_lambda#17]
### Steps to reproduce
Certain tokens that don't follow the regex but are valid log tokens in logentries are not accepted (invalid)
Difficult to reproduce because I dont want to give my token. But you can check against the schema for defining tokens.
### Expected Behaviour
It should validate tokens
### Actual Behaviour
Doesn't pass and therefore lambda function outputs a "process exited before completing request" error
### Workaround(s)
Tokens are hardcoded so commenting out the validate_uuid function calls allows the token to be accepted.

Probably need to update regex schema for logentries tokens

**Comment by ardimehist-r7** [comment]
@roshanjrajan the validation is due to be updated to use `uuid.uuid` rather than regex,
Could you please open a support ticket with support@logentries.com as well, so we can test the function with the token of your target log?
Thanks

**Comment by roshanjrajan** [comment]
@ardimehist-r7  I don't have access to a logentries account anymore so you are going to need to find some other way to test that function.

**Comment by ardimehist-r7** [comment]
@roshanjrajan no worries, thanks for reporting the issue!

**Comment by omgapuppy** [comment]
addressed in https://github.com/rapid7/le_lambda/pull/18
