### ISSUE TITLE
Data should not be send to data.logentries port 80 but data.logentries.com 2000

### ISSUE THREAD

**Issue by udangel-r7** [logentries/le_lambda#2]
data.logentries.com on port 80 should not be used for non http put traffic (which is deprecated). Instead we have to send it encrypted to data.logentries.com to port 20000

**Comment by omgapuppy** [comment]
@udangel-r7 added SSL support, certs & updated readme accordingly in [latest commit](https://github.com/logentries/le_lambda/commit/06f3151eb56972a7ba085fc4d1f7166c2c6ff711)
